"""Control Theory — 12 base formulae, 7 rearrangements.
Generated by researcher/_generate.py from Archimedes/CANONICAL_MATHS.md —
equational decomposition: each equation solved for every variable with a
closed form. Do not edit by hand; re-run the generator.
"""
from ...mathdef import MathDef

CATEGORY = 'control_theory'
PAGE = {"title": 'Control Theory', "jurisdiction": 'linear',
        "blurb": "Control Theory: 12 standard relations, each rearranged for "
                 "every variable that has a closed form (7 derived forms)."}
JURISDICTION = {'control_theory.first_order_transfer_function': 'linear', 'control_theory.first_order_transfer_function__Kg': 'linear', 'control_theory.first_order_transfer_function__s': 'linear', 'control_theory.first_order_transfer_function__taus': 'linear', 'control_theory.second_order_transfer_function': 'linear', 'control_theory.closed_loop_transfer_function': 'linear', 'control_theory.closed_loop_transfer_function__Gs': 'linear', 'control_theory.closed_loop_transfer_function__Hs': 'linear', 'control_theory.steady_state_error_step_type_0': 'linear', 'control_theory.steady_state_error_step_type_0__Kp': 'linear', 'control_theory.damping_ratio_from_overshoot': 'linear', 'control_theory.settling_time_2': 'linear', 'control_theory.peak_time': 'linear', 'control_theory.percent_overshoot': 'linear', 'control_theory.pid_controller': 'linear', 'control_theory.phase_margin_condition': 'linear', 'control_theory.phase_margin_condition__arg_GH': 'linear', 'control_theory.gain_margin': 'linear', 'control_theory.routh_first_column_2nd_order': 'linear'}

DEFS = [
    MathDef(id='control_theory.first_order_transfer_function', category='control_theory', name='first-order transfer function',
            expr='Gs = Kg/(taus*s + 1)', variables=['Gs', 'Kg', 's', 'taus'],
            solvable_for={}),
    MathDef(id='control_theory.first_order_transfer_function__Kg', category='control_theory', name='first-order transfer function — solved for Kg',
            expr='Kg = Gs*(s*taus + 1)', variables=['Gs', 'Kg', 's', 'taus'],
            solvable_for={}),
    MathDef(id='control_theory.first_order_transfer_function__s', category='control_theory', name='first-order transfer function — solved for s',
            expr='s = (-Gs + Kg)/(Gs*taus)', variables=['Gs', 'Kg', 's', 'taus'],
            solvable_for={}),
    MathDef(id='control_theory.first_order_transfer_function__taus', category='control_theory', name='first-order transfer function — solved for taus',
            expr='taus = (-Gs + Kg)/(Gs*s)', variables=['Gs', 'Kg', 's', 'taus'],
            solvable_for={}),
    MathDef(id='control_theory.second_order_transfer_function', category='control_theory', name='second-order transfer function',
            expr='Gs = wn^2/(s^2 + 2*zeta*wn*s + wn^2)', variables=[],
            solvable_for={}),
    MathDef(id='control_theory.closed_loop_transfer_function', category='control_theory', name='closed-loop transfer function',
            expr='Tcl = Gs/(1 + Gs*Hs)', variables=['Gs', 'Hs', 'Tcl'],
            solvable_for={}),
    MathDef(id='control_theory.closed_loop_transfer_function__Gs', category='control_theory', name='closed-loop transfer function — solved for Gs',
            expr='Gs = -Tcl/(Hs*Tcl - 1)', variables=['Gs', 'Hs', 'Tcl'],
            solvable_for={}),
    MathDef(id='control_theory.closed_loop_transfer_function__Hs', category='control_theory', name='closed-loop transfer function — solved for Hs',
            expr='Hs = (Gs - Tcl)/(Gs*Tcl)', variables=['Gs', 'Hs', 'Tcl'],
            solvable_for={}),
    MathDef(id='control_theory.steady_state_error_step_type_0', category='control_theory', name='steady-state error (step, type 0)',
            expr='ess = 1/(1 + Kp)', variables=['Kp', 'ess'],
            solvable_for={}),
    MathDef(id='control_theory.steady_state_error_step_type_0__Kp', category='control_theory', name='steady-state error (step, type 0) — solved for Kp',
            expr='Kp = (1 - ess)/ess', variables=['Kp', 'ess'],
            solvable_for={}),
    MathDef(id='control_theory.damping_ratio_from_overshoot', category='control_theory', name='damping ratio from overshoot',
            expr='zeta = -log(Mp)/sqrt(pi^2 + log(Mp)^2)', variables=[],
            solvable_for={}),
    MathDef(id='control_theory.settling_time_2', category='control_theory', name='settling time (2%)',
            expr='ts = 4/(zeta*wn)', variables=[],
            solvable_for={}),
    MathDef(id='control_theory.peak_time', category='control_theory', name='peak time',
            expr='tp = pi/(wn*sqrt(1 - zeta^2))', variables=[],
            solvable_for={}),
    MathDef(id='control_theory.percent_overshoot', category='control_theory', name='percent overshoot',
            expr='Mp = exp(-pi*zeta/sqrt(1 - zeta^2))', variables=[],
            solvable_for={}),
    MathDef(id='control_theory.pid_controller', category='control_theory', name='PID controller',
            expr='u = Kp*e + Ki*Integral(e, t) + Kd*de_dt', variables=['Kd', 'Ki', 'Kp', 'de_dt', 'e', 't', 'u'],
            solvable_for={}),
    MathDef(id='control_theory.phase_margin_condition', category='control_theory', name='phase margin condition',
            expr='PM = 180 + arg_GH', variables=['PM', 'arg_GH'],
            solvable_for={}),
    MathDef(id='control_theory.phase_margin_condition__arg_GH', category='control_theory', name='phase margin condition — solved for arg_GH',
            expr='arg_GH = PM - 180', variables=['PM', 'arg_GH'],
            solvable_for={}),
    MathDef(id='control_theory.gain_margin', category='control_theory', name='gain margin',
            expr='GM = 1/Abs(GH_at_180)', variables=['GH_at_180', 'GM'],
            solvable_for={}),
    MathDef(id='control_theory.routh_first_column_2nd_order', category='control_theory', name='Routh first column (2nd order)',
            expr='a1*a2 - a0*a3 > 0', variables=['a0', 'a1', 'a2', 'a3'],
            solvable_for={}),
]
