"""Transforms — 10 base formulae, 9 rearrangements.
Generated by researcher/_generate.py from Archimedes/CANONICAL_MATHS.md —
equational decomposition: each equation solved for every variable with a
closed form. Do not edit by hand; re-run the generator.
"""
from ...mathdef import MathDef

CATEGORY = 'transforms'
PAGE = {"title": 'Transforms', "jurisdiction": 'pure',
        "blurb": "Transforms: 10 standard relations, each rearranged for "
                 "every variable that has a closed form (9 derived forms)."}
JURISDICTION = {'transforms.fourier_transform': 'pure', 'transforms.inverse_fourier_transform': 'pure', 'transforms.laplace_transform': 'pure', 'transforms.laplace_of_a_derivative': 'linear', 'transforms.laplace_of_a_derivative__F': 'linear', 'transforms.laplace_of_a_derivative__f0': 'linear', 'transforms.laplace_of_a_derivative__s': 'linear', 'transforms.parseval_s_theorem': 'pure', 'transforms.convolution_theorem': 'linear', 'transforms.convolution_theorem__F': 'linear', 'transforms.convolution_theorem__G': 'linear', 'transforms.z_transform': 'pure', 'transforms.dft_coefficient': 'numerical', 'transforms.sampling_nyquist': 'engineering', 'transforms.sampling_nyquist__fmax': 'engineering', 'transforms.discrete_time_shift': 'linear', 'transforms.discrete_time_shift__X': 'linear', 'transforms.discrete_time_shift__k': 'linear', 'transforms.discrete_time_shift__z': 'linear'}

DEFS = [
    MathDef(id='transforms.fourier_transform', category='transforms', name='Fourier transform',
            expr='F = Integral(f*exp(-I*omega*t), (t, -oo, oo))', variables=['F', 'I', 'f', 'omega', 'oo'],
            solvable_for={}),
    MathDef(id='transforms.inverse_fourier_transform', category='transforms', name='inverse Fourier transform',
            expr='f = (1/(2*pi))*Integral(F*exp(I*omega*t), (omega, -oo, oo))', variables=['F', 'I', 'f', 'oo', 't'],
            solvable_for={}),
    MathDef(id='transforms.laplace_transform', category='transforms', name='Laplace transform',
            expr='F = Integral(f*exp(-s*t), (t, 0, oo))', variables=['F', 'f', 'oo', 's'],
            solvable_for={}),
    MathDef(id='transforms.laplace_of_a_derivative', category='transforms', name='Laplace of a derivative',
            expr='Lfp = s*F - f0', variables=['F', 'Lfp', 'f0', 's'],
            solvable_for={}),
    MathDef(id='transforms.laplace_of_a_derivative__F', category='transforms', name='Laplace of a derivative — solved for F',
            expr='F = (Lfp + f0)/s', variables=['F', 'Lfp', 'f0', 's'],
            solvable_for={}),
    MathDef(id='transforms.laplace_of_a_derivative__f0', category='transforms', name='Laplace of a derivative — solved for f0',
            expr='f0 = F*s - Lfp', variables=['F', 'Lfp', 'f0', 's'],
            solvable_for={}),
    MathDef(id='transforms.laplace_of_a_derivative__s', category='transforms', name='Laplace of a derivative — solved for s',
            expr='s = (Lfp + f0)/F', variables=['F', 'Lfp', 'f0', 's'],
            solvable_for={}),
    MathDef(id='transforms.parseval_s_theorem', category='transforms', name="Parseval's theorem",
            expr='Integral(Abs(f)^2, t) = (1/(2*pi))*Integral(Abs(F)^2, omega)', variables=['F', 'f', 'omega', 't'],
            solvable_for={}),
    MathDef(id='transforms.convolution_theorem', category='transforms', name='convolution theorem',
            expr='L_fg = F*G', variables=['F', 'G', 'L_fg'],
            solvable_for={}),
    MathDef(id='transforms.convolution_theorem__F', category='transforms', name='convolution theorem — solved for F',
            expr='F = L_fg/G', variables=['F', 'G', 'L_fg'],
            solvable_for={}),
    MathDef(id='transforms.convolution_theorem__G', category='transforms', name='convolution theorem — solved for G',
            expr='G = L_fg/F', variables=['F', 'G', 'L_fg'],
            solvable_for={}),
    MathDef(id='transforms.z_transform', category='transforms', name='Z-transform',
            expr='X = Sum(x*z^(-n), (n, 0, oo))', variables=['X', 'oo', 'x', 'z'],
            solvable_for={}),
    MathDef(id='transforms.dft_coefficient', category='transforms', name='DFT coefficient',
            expr='Xk = Sum(x*exp(-2*pi*I*k*n/N), (n, 0, N - 1))', variables=['I', 'N', 'Xk', 'k', 'x'],
            solvable_for={}),
    MathDef(id='transforms.sampling_nyquist', category='transforms', name='sampling (Nyquist)',
            expr='fs = 2*fmax', variables=['fmax', 'fs'],
            solvable_for={}),
    MathDef(id='transforms.sampling_nyquist__fmax', category='transforms', name='sampling (Nyquist) — solved for fmax',
            expr='fmax = fs/2', variables=['fmax', 'fs'],
            solvable_for={}),
    MathDef(id='transforms.discrete_time_shift', category='transforms', name='discrete-time shift',
            expr='Z_shift = z^(-k)*X', variables=['X', 'Z_shift', 'k', 'z'],
            solvable_for={}),
    MathDef(id='transforms.discrete_time_shift__X', category='transforms', name='discrete-time shift — solved for X',
            expr='X = Z_shift*z**k', variables=['X', 'Z_shift', 'k', 'z'],
            solvable_for={}),
    MathDef(id='transforms.discrete_time_shift__k', category='transforms', name='discrete-time shift — solved for k',
            expr='k = log(X/Z_shift)/log(z)', variables=['X', 'Z_shift', 'k', 'z'],
            solvable_for={}),
    MathDef(id='transforms.discrete_time_shift__z', category='transforms', name='discrete-time shift — solved for z',
            expr='z = (X/Z_shift)**(1/k)', variables=['X', 'Z_shift', 'k', 'z'],
            solvable_for={}),
]
