"""Trigonometry — 11 base formulae, 7 rearrangements.
Generated by researcher/_generate.py from Archimedes/CANONICAL_MATHS.md —
equational decomposition: each equation solved for every variable with a
closed form. Do not edit by hand; re-run the generator.
"""
from ...mathdef import MathDef

CATEGORY = 'trigonometry'
PAGE = {"title": 'Trigonometry', "jurisdiction": 'pure',
        "blurb": "Trigonometry: 11 standard relations, each rearranged for "
                 "every variable that has a closed form (7 derived forms)."}
JURISDICTION = {'trigonometry.pythagorean_identity': 'pure', 'trigonometry.tangent_identity': 'pure', 'trigonometry.angle_sum_sine': 'pure', 'trigonometry.angle_sum_cosine': 'pure', 'trigonometry.double_angle_sine': 'pure', 'trigonometry.double_angle_cosine': 'pure', 'trigonometry.half_angle_sine': 'pure', 'trigonometry.product_to_sum': 'pure', 'trigonometry.law_of_tangents': 'pure', 'trigonometry.law_of_tangents__a': 'pure', 'trigonometry.law_of_tangents__b': 'pure', 'trigonometry.arc_length_radians': 'pure', 'trigonometry.arc_length_radians__r': 'pure', 'trigonometry.arc_length_radians__theta': 'pure', 'trigonometry.sector_area': 'pure', 'trigonometry.sector_area__r_0': 'pure', 'trigonometry.sector_area__r_1': 'pure', 'trigonometry.sector_area__theta': 'pure'}

DEFS = [
    MathDef(id='trigonometry.pythagorean_identity', category='trigonometry', name='Pythagorean identity',
            expr='sin(x)^2 + cos(x)^2 = 1', variables=['x'],
            solvable_for={}),
    MathDef(id='trigonometry.tangent_identity', category='trigonometry', name='tangent identity',
            expr='tan(x) = sin(x)/cos(x)', variables=['x'],
            solvable_for={}),
    MathDef(id='trigonometry.angle_sum_sine', category='trigonometry', name='angle sum (sine)',
            expr='sin(a + b) = sin(a)*cos(b) + cos(a)*sin(b)', variables=['a', 'b'],
            solvable_for={}),
    MathDef(id='trigonometry.angle_sum_cosine', category='trigonometry', name='angle sum (cosine)',
            expr='cos(a + b) = cos(a)*cos(b) - sin(a)*sin(b)', variables=['a', 'b'],
            solvable_for={}),
    MathDef(id='trigonometry.double_angle_sine', category='trigonometry', name='double angle (sine)',
            expr='sin(2*x) = 2*sin(x)*cos(x)', variables=['x'],
            solvable_for={}),
    MathDef(id='trigonometry.double_angle_cosine', category='trigonometry', name='double angle (cosine)',
            expr='cos(2*x) = 1 - 2*sin(x)^2', variables=['x'],
            solvable_for={}),
    MathDef(id='trigonometry.half_angle_sine', category='trigonometry', name='half angle (sine)',
            expr='sin(x/2) = sqrt((1 - cos(x))/2)', variables=['x'],
            solvable_for={}),
    MathDef(id='trigonometry.product_to_sum', category='trigonometry', name='product to sum',
            expr='sin(a)*cos(b) = (sin(a + b) + sin(a - b))/2', variables=['a', 'b'],
            solvable_for={}),
    MathDef(id='trigonometry.law_of_tangents', category='trigonometry', name='law of tangents',
            expr='(a - b)/(a + b) = tan((A - B)/2)/tan((A + B)/2)', variables=['A', 'B', 'a', 'b'],
            solvable_for={}),
    MathDef(id='trigonometry.law_of_tangents__a', category='trigonometry', name='law of tangents — solved for a',
            expr='a = b*(tan(A/2 - B/2) + tan(A/2 + B/2))/(-tan(A/2 - B/2) + tan(A/2 + B/2))', variables=['A', 'B', 'a', 'b'],
            solvable_for={}),
    MathDef(id='trigonometry.law_of_tangents__b', category='trigonometry', name='law of tangents — solved for b',
            expr='b = a*(-tan(A/2 - B/2) + tan(A/2 + B/2))/(tan(A/2 - B/2) + tan(A/2 + B/2))', variables=['A', 'B', 'a', 'b'],
            solvable_for={}),
    MathDef(id='trigonometry.arc_length_radians', category='trigonometry', name='arc length (radians)',
            expr='s = r*theta', variables=['r', 's', 'theta'],
            solvable_for={}),
    MathDef(id='trigonometry.arc_length_radians__r', category='trigonometry', name='arc length (radians) — solved for r',
            expr='r = s/theta', variables=['r', 's', 'theta'],
            solvable_for={}),
    MathDef(id='trigonometry.arc_length_radians__theta', category='trigonometry', name='arc length (radians) — solved for theta',
            expr='theta = s/r', variables=['r', 's', 'theta'],
            solvable_for={}),
    MathDef(id='trigonometry.sector_area', category='trigonometry', name='sector area',
            expr='A = r^2*theta/2', variables=['A', 'r', 'theta'],
            solvable_for={}),
    MathDef(id='trigonometry.sector_area__r_0', category='trigonometry', name='sector area — solved for r',
            expr='r = -sqrt(2)*sqrt(A/theta)', variables=['A', 'r', 'theta'],
            solvable_for={}),
    MathDef(id='trigonometry.sector_area__r_1', category='trigonometry', name='sector area — solved for r',
            expr='r = sqrt(2)*sqrt(A/theta)', variables=['A', 'r', 'theta'],
            solvable_for={}),
    MathDef(id='trigonometry.sector_area__theta', category='trigonometry', name='sector area — solved for theta',
            expr='theta = 2*A/r**2', variables=['A', 'r', 'theta'],
            solvable_for={}),
]
